package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"io/ioutil"
	"math/rand"
	"os/exec"
	"path/filepath"

	"github.com/valyala/fasttemplate"
)

func main() {
	args := os.Args[1:]
	if len(args) != 1 {
		panic("fn expected")
	}
	fn := args[0]

	ext := filepath.Ext(fn)
	if ext != ".go" {
		panic("*.go file expected")
	}

	fnWOExt := fn[0 : len(fn)-len(ext)]
	fnOut := fnWOExt + "_logs.go"
	fmt.Println(fnOut)

	data, err := ioutil.ReadFile(fn)
	if err != nil {
		panic(err)
	}

	src, dest := string(data), ""

	hTmp := fasttemplate.New(headerTemplate, "{{", "}}")
	iTmp := fasttemplate.New(initTemplate, "{{", "}}")
	sTmp := fasttemplate.New(structLoggerTemplate, "{{", "}}")

	hasPkg := false
	wasLoggerTag := false

	scanner := bufio.NewScanner(strings.NewReader(src))
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "package") {
			if hasPkg {
				panic("multiple package declaration")
			}

			hasPkg = true
			pkgName := strings.TrimLeft(line, "package ")
			dest += hTmp.ExecuteString(map[string]interface{}{
				"package": pkgName,
			})

			dest += iTmp.ExecuteString(map[string]interface{}{
				"componentName": fmt.Sprintf("componentName%d", rand.Uint64()),
			})

			continue
		}

		if wasLoggerTag {
			if !strings.Contains(line, "type") || !strings.Contains(line, "struct") {
				panic("logger tag should be followed by struct declaration")
			}

			i1 := len("type ")
			i2 := strings.Index(line[i1:], " ") + i1
			structName := line[i1:i2]

			dest += "\n" + sTmp.ExecuteString(map[string]interface{}{
				"structName": strings.ToLower(structName),
				"StructName": structName,
			})

			wasLoggerTag = false
		}

		if strings.HasPrefix(line, "// struct-logs-gen:gen") {
			if wasLoggerTag {
				panic("multiple logger tags")
			}
			wasLoggerTag = true
		}
	}

	err = ioutil.WriteFile(fnOut, []byte(dest), 0644)
	if err != nil {
		panic(err)
	}

	cmd := exec.Command("go", "fmt", fnOut)
	err = cmd.Run()
	if err != nil {
		panic(err)
	}
}

const (
	headerTemplate = `
		// Code generated by struct-logs-gen. DO NOT EDIT.
		package {{package}}

		import (
			"reflect"
			"strings"

			"go/importer"
			"go/types"

			"github.com/studtool/common/logs"
		)
	`

	initTemplate = `
		var (
			{{componentName}} = ""
		)
		
		func init() {
			const prefix = "github.com/studtool/"

			p := reflect.TypeOf({{componentName}}).PkgPath()
			if !strings.Contains(p, prefix) {
				panic("not a studtool service")
			}

			i1 := strings.Index(p, prefix) + len(prefix)
			i2 := strings.Index(p[i1:], "/") + i1
			p = p[i1:i2]

			pkg, err := importer.Default().Import(prefix + {{componentName}} + "/config")
			if err != nil {
				panic(err)
			}

			scope := pkg.Scope()
			for _, name := range scope.Names() {
				// config.Component should exist
				if name == "Component" {
					obj := scope.Lookup(name)
					if tn, ok := obj.Type().(*types.Named); !ok {
						panic(!ok) //TODO
					}
				}
			}
		}
	`

	structLoggerTemplate = `
		var {{structName}}Logger = &logs.StructLogger{}

		func (_ *{{StructName}}) GetStructLogger() logs.Logger {
			return {{structName}}Logger
		}
	`
)
